/**
 * Provider registry — the hand-maintained source for BOTH `data/providers.json` (HOW to connect:
 * baseUrl / adapterFamily per endpoint, website, apiFeatures) and `data/provider-models.json` (WHICH
 * models a provider serves + per-provider pricing/overrides). Both JSON files are generated by
 * `scripts/generate-catalog.ts` — never hand-edit them; edit a provider here and regenerate.
 *
 * A provider's CONNECTION config is the `ProviderConfig` shape (minus `description`, which is templated
 * as `"{name} - AI model provider"`). The GENERATION-only fields below (`modelsDevProvider` / `fetchModels`
 * / `overrides`) drive `provider-models.json` and are NOT emitted to `providers.json`.
 */
import type { ApiFeatures, ProviderConfig, ProviderReasoningFormat, ServerToolConfig } from '../schemas/provider'
import type { ProviderModelOverride } from '../schemas/provider-models'

/**
 * Connection config emitted to `providers.json`. `description` is templated, so it's omitted here;
 * `endpointConfigs` is relaxed to a partial map (a provider declares only the 1–2 endpoints it speaks);
 * `defaultChatEndpoint` is optional (dynamic/local providers like ollama/lmstudio/new-api omit it).
 */
type ProviderConnection = Omit<
  ProviderConfig,
  | 'description'
  | 'endpointConfigs'
  | 'defaultChatEndpoint'
  | 'apiFeatures'
  | 'modelListSource'
  | 'authOptional'
  | 'serverTools'
> & {
  endpointConfigs: Partial<ProviderConfig['endpointConfigs']>
  defaultChatEndpoint?: ProviderConfig['defaultChatEndpoint']
  /** Defaults to `api`; only registry-backed providers need to declare it. */
  modelListSource?: ProviderConfig['modelListSource']
  /** Defaults to `false`; only credential-free local providers declare it. */
  authOptional?: ProviderConfig['authOptional']
  /** Defaults to `[]`; only providers that natively serve built-in tools declare it. */
  serverTools?: ProviderServerToolConfig[]
  /** Only the non-default flags are declared; the schema fills the rest at load time. */
  apiFeatures?: Partial<ApiFeatures>
}

/**
 * Provider-authored server-tool declaration. Model selectors are generation-only:
 * they compile to exact provider/model/tool rows and are omitted from providers.json.
 */
export type ProviderServerToolConfig = ServerToolConfig & {
  /** Canonical model-id prefixes served by this provider. */
  modelIdPrefixes?: string[]
  /** Exact canonical model ids served by this provider. */
  modelIds?: string[]
  /** Exact image-generation models explicitly allowed despite the default image exclusion. */
  imageModelIds?: string[]
}

/** A provider as emitted to `providers.json`: the connection config plus its templated `description`. */
export type ProviderEntry = Omit<ProviderConnection, 'serverTools'> & {
  description: string
  serverTools?: ProviderConfig['serverTools']
}

/** A provider's website links (official / docs / apiKey / models). */
type ProviderWebsite = ProviderConfig['metadata']['website']

export interface Provider extends ProviderConnection {
  /** models.dev provider key whose listing is this provider's served catalog (with per-model pricing). */
  modelsDevProvider?: string
  /** …or fetch the served list from the provider's own `/models` API (see `../creators/_api.ts`). */
  fetchModels?: () => Promise<{ id: string }[]>
  /** Manual overrides — for exact model ids, pricing, transports, reasoning contracts, and status. */
  overrides?: Partial<ProviderModelOverride>[]
}

export function defineProvider(p: Provider): Provider {
  return p
}

/** Generation-only fields shared by every provider, kept out of the connection config. */
type GenFields = Pick<Provider, 'modelsDevProvider' | 'fetchModels' | 'overrides'>

/**
 * Helper for the common OpenAI-compatible provider: `openai-chat-completions` over `baseUrl` (and an
 * optional `anthropic-messages` mirror), defaulting chat to `openai-chat-completions`. Covers ~half the
 * registry; providers with a bespoke adapterFamily or extra endpoints use `defineProvider` directly.
 */
export function openaiCompatible(
  p: {
    id: string
    name: string
    baseUrl: string
    anthropic?: string
    website: ProviderWebsite
    apiFeatures?: Partial<ApiFeatures>
    presetProviderId?: string
    /**
     * The chat endpoint's base protocol plus any endpoint-wide wire override.
     * Exact provider-model exceptions belong in endpoint-keyed `reasoningContracts`.
     */
    reasoningFormat?: ProviderReasoningFormat
    authOptional?: ProviderConfig['authOptional']
    serverTools?: ProviderServerToolConfig[]
  } & GenFields
): Provider {
  const endpointConfigs: ProviderConnection['endpointConfigs'] = {
    'openai-chat-completions': {
      adapterFamily: 'openai-compatible',
      baseUrl: p.baseUrl,
      ...(p.reasoningFormat ? { reasoningFormat: p.reasoningFormat } : {})
    }
  }
  if (p.anthropic) endpointConfigs['anthropic-messages'] = { adapterFamily: 'anthropic', baseUrl: p.anthropic }
  return defineProvider({
    id: p.id,
    name: p.name,
    defaultChatEndpoint: 'openai-chat-completions',
    endpointConfigs,
    metadata: { website: p.website },
    ...(p.apiFeatures ? { apiFeatures: p.apiFeatures } : {}),
    ...(p.authOptional ? { authOptional: p.authOptional } : {}),
    ...(p.serverTools ? { serverTools: p.serverTools } : {}),
    ...(p.presetProviderId ? { presetProviderId: p.presetProviderId } : {}),
    ...(p.modelsDevProvider ? { modelsDevProvider: p.modelsDevProvider } : {}),
    ...(p.fetchModels ? { fetchModels: p.fetchModels } : {}),
    ...(p.overrides ? { overrides: p.overrides } : {})
  })
}
