/**
 * Auto-generated icon meta catalog for synchronous runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Generated at: 2026-08-10T12:29:43.664Z
 * Total icons: 168
 */
import { type IconMeta } from '../types'
import { meta as aceMeta } from './ace/meta'
import { meta as adobeMeta } from './adobe/meta'
import { meta as ai2Meta } from './ai2/meta'
import { meta as ai21Meta } from './ai21/meta'
import { meta as ai360Meta } from './ai360/meta'
import { meta as aihubmixMeta } from './aihubmix/meta'
import { meta as aimassMeta } from './aimass/meta'
import { meta as aionlabsMeta } from './aionlabs/meta'
import { meta as anthropicMeta } from './anthropic/meta'
import { meta as arceeMeta } from './arcee/meta'
import { meta as assemblyaiMeta } from './assemblyai/meta'
import { meta as awsMeta } from './aws/meta'
import { meta as ayaMeta } from './aya/meta'
import { meta as baaiMeta } from './baai/meta'
import { meta as baichuanMeta } from './baichuan/meta'
import { meta as baiducloudMeta } from './baiducloud/meta'
import { meta as bilibiliMeta } from './bilibili/meta'
import { meta as bilibiliindexMeta } from './bilibiliindex/meta'
import { meta as burncloudMeta } from './burncloud/meta'
import { meta as bytedanceMeta } from './bytedance/meta'
import { meta as chatglmMeta } from './chatglm/meta'
import { meta as claudeMeta } from './claude/meta'
import { meta as codegeexMeta } from './codegeex/meta'
import { meta as cogviewMeta } from './cogview/meta'
import { meta as cohereMeta } from './cohere/meta'
import { meta as dalleMeta } from './dalle/meta'
import { meta as dbrxMeta } from './dbrx/meta'
import { meta as deepcogitoMeta } from './deepcogito/meta'
import { meta as deepmindMeta } from './deepmind/meta'
import { meta as deepseekMeta } from './deepseek/meta'
import { meta as dolphinMeta } from './dolphin/meta'
import { meta as doubaoMeta } from './doubao/meta'
import { meta as essentialaiMeta } from './essentialai/meta'
import { meta as fireworksMeta } from './fireworks/meta'
import { meta as fishaudioMeta } from './fishaudio/meta'
import { meta as fluxMeta } from './flux/meta'
import { meta as geminiMeta } from './gemini/meta'
import { meta as gemmaMeta } from './gemma/meta'
import { meta as glmMeta } from './glm/meta'
import { meta as glmvMeta } from './glmv/meta'
import { meta as googleMeta } from './google/meta'
import { meta as gpt35TurboMeta } from './gpt-3-5-turbo/meta'
import { meta as gpt4Meta } from './gpt-4/meta'
import { meta as gpt41Meta } from './gpt-4-1/meta'
import { meta as gpt41MiniMeta } from './gpt-4-1-mini/meta'
import { meta as gpt41NanoMeta } from './gpt-4-1-nano/meta'
import { meta as gpt45PreviewMeta } from './gpt-4-5-preview/meta'
import { meta as gpt4TurboMeta } from './gpt-4-turbo/meta'
import { meta as gpt4TurboPreviewMeta } from './gpt-4-turbo-preview/meta'
import { meta as gpt4oMeta } from './gpt-4o/meta'
import { meta as gpt4oAudioPreviewMeta } from './gpt-4o-audio-preview/meta'
import { meta as gpt4oMiniMeta } from './gpt-4o-mini/meta'
import { meta as gpt4oMiniAudioPreviewMeta } from './gpt-4o-mini-audio-preview/meta'
import { meta as gpt4oMiniRealtimePreviewMeta } from './gpt-4o-mini-realtime-preview/meta'
import { meta as gpt4oMiniSearchPreviewMeta } from './gpt-4o-mini-search-preview/meta'
import { meta as gpt4oMiniTranscribeMeta } from './gpt-4o-mini-transcribe/meta'
import { meta as gpt4oMiniTtsMeta } from './gpt-4o-mini-tts/meta'
import { meta as gpt4oRealtimePreviewMeta } from './gpt-4o-realtime-preview/meta'
import { meta as gpt4oSearchPreviewMeta } from './gpt-4o-search-preview/meta'
import { meta as gpt4oTranscribeMeta } from './gpt-4o-transcribe/meta'
import { meta as gpt4oTranscribeDiarizeMeta } from './gpt-4o-transcribe-diarize/meta'
import { meta as gpt5Meta } from './gpt-5/meta'
import { meta as gpt51Meta } from './gpt-5-1/meta'
import { meta as gpt51ChatMeta } from './gpt-5-1-chat/meta'
import { meta as gpt51ChatLatestMeta } from './gpt-5-1-chat-latest/meta'
import { meta as gpt51CodexMeta } from './gpt-5-1-codex/meta'
import { meta as gpt51CodexMaxMeta } from './gpt-5-1-codex-max/meta'
import { meta as gpt51CodexMiniMeta } from './gpt-5-1-codex-mini/meta'
import { meta as gpt52Meta } from './gpt-5-2/meta'
import { meta as gpt52ChatLatestMeta } from './gpt-5-2-chat-latest/meta'
import { meta as gpt52CodexMeta } from './gpt-5-2-codex/meta'
import { meta as gpt52ProMeta } from './gpt-5-2-pro/meta'
import { meta as gpt53ChatLatestMeta } from './gpt-5-3-chat-latest/meta'
import { meta as gpt53CodexMeta } from './gpt-5-3-codex/meta'
import { meta as gpt54Meta } from './gpt-5-4/meta'
import { meta as gpt54MiniMeta } from './gpt-5-4-mini/meta'
import { meta as gpt54NanoMeta } from './gpt-5-4-nano/meta'
import { meta as gpt54ProMeta } from './gpt-5-4-pro/meta'
import { meta as gpt55Meta } from './gpt-5-5/meta'
import { meta as gpt55ProMeta } from './gpt-5-5-pro/meta'
import { meta as gpt56LunaMeta } from './gpt-5-6-luna/meta'
import { meta as gpt56SolMeta } from './gpt-5-6-sol/meta'
import { meta as gpt56TerraMeta } from './gpt-5-6-terra/meta'
import { meta as gpt5ChatMeta } from './gpt-5-chat/meta'
import { meta as gpt5ChatLatestMeta } from './gpt-5-chat-latest/meta'
import { meta as gpt5CodexMeta } from './gpt-5-codex/meta'
import { meta as gpt5MiniMeta } from './gpt-5-mini/meta'
import { meta as gpt5NanoMeta } from './gpt-5-nano/meta'
import { meta as gpt5ProMeta } from './gpt-5-pro/meta'
import { meta as gptAudioMeta } from './gpt-audio/meta'
import { meta as gptAudio15Meta } from './gpt-audio-1-5/meta'
import { meta as gptAudioMiniMeta } from './gpt-audio-mini/meta'
import { meta as gptImage1Meta } from './gpt-image-1/meta'
import { meta as gptImage15Meta } from './gpt-image-1-5/meta'
import { meta as gptImage1MiniMeta } from './gpt-image-1-mini/meta'
import { meta as gptImage2Meta } from './gpt-image-2/meta'
import { meta as gptOss20bMeta } from './gpt-oss-20b/meta'
import { meta as gptOss120bMeta } from './gpt-oss-120b/meta'
import { meta as gptRealtimeMeta } from './gpt-realtime/meta'
import { meta as gptRealtime15Meta } from './gpt-realtime-1-5/meta'
import { meta as gptRealtime2Meta } from './gpt-realtime-2/meta'
import { meta as gptRealtime21Meta } from './gpt-realtime-2-1/meta'
import { meta as gptRealtime21MiniMeta } from './gpt-realtime-2-1-mini/meta'
import { meta as gptRealtimeMiniMeta } from './gpt-realtime-mini/meta'
import { meta as gptRealtimeTranslateMeta } from './gpt-realtime-translate/meta'
import { meta as gptRealtimeWhisperMeta } from './gpt-realtime-whisper/meta'
import { meta as grokMeta } from './grok/meta'
import { meta as hailuoMeta } from './hailuo/meta'
import { meta as happyhorseMeta } from './happyhorse/meta'
import { meta as hunyuanMeta } from './hunyuan/meta'
import { meta as ibmMeta } from './ibm/meta'
import { meta as ideogramMeta } from './ideogram/meta'
import { meta as inceptionMeta } from './inception/meta'
import { meta as inflectionMeta } from './inflection/meta'
import { meta as internlmMeta } from './internlm/meta'
import { meta as jimengMeta } from './jimeng/meta'
import { meta as jinaMeta } from './jina/meta'
import { meta as kimiMeta } from './kimi/meta'
import { meta as klingMeta } from './kling/meta'
import { meta as kolorsMeta } from './kolors/meta'
import { meta as kwaipilotMeta } from './kwaipilot/meta'
import { meta as lgMeta } from './lg/meta'
import { meta as lingMeta } from './ling/meta'
import { meta as liquidMeta } from './liquid/meta'
import { meta as llavaMeta } from './llava/meta'
import { meta as longcatMeta } from './longcat/meta'
import { meta as menloMeta } from './menlo/meta'
import { meta as metaMeta } from './meta/meta'
import { meta as microsoftMeta } from './microsoft/meta'
import { meta as mimoMeta } from './mimo/meta'
import { meta as minimaxMeta } from './minimax/meta'
import { meta as mistralMeta } from './mistral/meta'
import { meta as moonshotMeta } from './moonshot/meta'
import { meta as morphMeta } from './morph/meta'
import { meta as nanobananaMeta } from './nanobanana/meta'
import { meta as nousresearchMeta } from './nousresearch/meta'
import { meta as novaMeta } from './nova/meta'
import { meta as nvidiaMeta } from './nvidia/meta'
import { meta as openaiMeta } from './openai/meta'
import { meta as openchatMeta } from './openchat/meta'
import { meta as openrouterMeta } from './openrouter/meta'
import { meta as palmMeta } from './palm/meta'
import { meta as perplexityMeta } from './perplexity/meta'
import { meta as phindMeta } from './phind/meta'
import { meta as poolsideMeta } from './poolside/meta'
import { meta as qiniuMeta } from './qiniu/meta'
import { meta as qwenMeta } from './qwen/meta'
import { meta as relaceMeta } from './relace/meta'
import { meta as rwkvMeta } from './rwkv/meta'
import { meta as sensenovaMeta } from './sensenova/meta'
import { meta as skyworkMeta } from './skywork/meta'
import { meta as soraMeta } from './sora/meta'
import { meta as sparkMeta } from './spark/meta'
import { meta as stabilityMeta } from './stability/meta'
import { meta as stepfunMeta } from './stepfun/meta'
import { meta as sunoMeta } from './suno/meta'
import { meta as tencentMeta } from './tencent/meta'
import { meta as tiiMeta } from './tii/meta'
import { meta as trinityMeta } from './trinity/meta'
import { meta as udioMeta } from './udio/meta'
import { meta as upstageMeta } from './upstage/meta'
import { meta as v0Meta } from './v0/meta'
import { meta as vertexaiMeta } from './vertexai/meta'
import { meta as voyageMeta } from './voyage/meta'
import { meta as wenxinMeta } from './wenxin/meta'
import { meta as xiaomimimoMeta } from './xiaomimimo/meta'
import { meta as yiMeta } from './yi/meta'
import { meta as zaiMeta } from './zai/meta'

export const MODEL_ICON_META_CATALOG = {
  ace: aceMeta,
  adobe: adobeMeta,
  ai2: ai2Meta,
  ai21: ai21Meta,
  ai360: ai360Meta,
  aihubmix: aihubmixMeta,
  aimass: aimassMeta,
  aionlabs: aionlabsMeta,
  anthropic: anthropicMeta,
  arcee: arceeMeta,
  assemblyai: assemblyaiMeta,
  aws: awsMeta,
  aya: ayaMeta,
  baai: baaiMeta,
  baichuan: baichuanMeta,
  baiducloud: baiducloudMeta,
  bilibili: bilibiliMeta,
  bilibiliindex: bilibiliindexMeta,
  burncloud: burncloudMeta,
  bytedance: bytedanceMeta,
  chatglm: chatglmMeta,
  claude: claudeMeta,
  codegeex: codegeexMeta,
  cogview: cogviewMeta,
  cohere: cohereMeta,
  dalle: dalleMeta,
  dbrx: dbrxMeta,
  deepcogito: deepcogitoMeta,
  deepmind: deepmindMeta,
  deepseek: deepseekMeta,
  dolphin: dolphinMeta,
  doubao: doubaoMeta,
  essentialai: essentialaiMeta,
  fireworks: fireworksMeta,
  fishaudio: fishaudioMeta,
  flux: fluxMeta,
  gemini: geminiMeta,
  gemma: gemmaMeta,
  glm: glmMeta,
  glmv: glmvMeta,
  google: googleMeta,
  'gpt-3-5-turbo': gpt35TurboMeta,
  'gpt-4': gpt4Meta,
  'gpt-4-1': gpt41Meta,
  'gpt-4-1-mini': gpt41MiniMeta,
  'gpt-4-1-nano': gpt41NanoMeta,
  'gpt-4-5-preview': gpt45PreviewMeta,
  'gpt-4-turbo': gpt4TurboMeta,
  'gpt-4-turbo-preview': gpt4TurboPreviewMeta,
  'gpt-4o': gpt4oMeta,
  'gpt-4o-audio-preview': gpt4oAudioPreviewMeta,
  'gpt-4o-mini': gpt4oMiniMeta,
  'gpt-4o-mini-audio-preview': gpt4oMiniAudioPreviewMeta,
  'gpt-4o-mini-realtime-preview': gpt4oMiniRealtimePreviewMeta,
  'gpt-4o-mini-search-preview': gpt4oMiniSearchPreviewMeta,
  'gpt-4o-mini-transcribe': gpt4oMiniTranscribeMeta,
  'gpt-4o-mini-tts': gpt4oMiniTtsMeta,
  'gpt-4o-realtime-preview': gpt4oRealtimePreviewMeta,
  'gpt-4o-search-preview': gpt4oSearchPreviewMeta,
  'gpt-4o-transcribe': gpt4oTranscribeMeta,
  'gpt-4o-transcribe-diarize': gpt4oTranscribeDiarizeMeta,
  'gpt-5': gpt5Meta,
  'gpt-5-1': gpt51Meta,
  'gpt-5-1-chat': gpt51ChatMeta,
  'gpt-5-1-chat-latest': gpt51ChatLatestMeta,
  'gpt-5-1-codex': gpt51CodexMeta,
  'gpt-5-1-codex-max': gpt51CodexMaxMeta,
  'gpt-5-1-codex-mini': gpt51CodexMiniMeta,
  'gpt-5-2': gpt52Meta,
  'gpt-5-2-chat-latest': gpt52ChatLatestMeta,
  'gpt-5-2-codex': gpt52CodexMeta,
  'gpt-5-2-pro': gpt52ProMeta,
  'gpt-5-3-chat-latest': gpt53ChatLatestMeta,
  'gpt-5-3-codex': gpt53CodexMeta,
  'gpt-5-4': gpt54Meta,
  'gpt-5-4-mini': gpt54MiniMeta,
  'gpt-5-4-nano': gpt54NanoMeta,
  'gpt-5-4-pro': gpt54ProMeta,
  'gpt-5-5': gpt55Meta,
  'gpt-5-5-pro': gpt55ProMeta,
  'gpt-5-6-luna': gpt56LunaMeta,
  'gpt-5-6-sol': gpt56SolMeta,
  'gpt-5-6-terra': gpt56TerraMeta,
  'gpt-5-chat': gpt5ChatMeta,
  'gpt-5-chat-latest': gpt5ChatLatestMeta,
  'gpt-5-codex': gpt5CodexMeta,
  'gpt-5-mini': gpt5MiniMeta,
  'gpt-5-nano': gpt5NanoMeta,
  'gpt-5-pro': gpt5ProMeta,
  'gpt-audio': gptAudioMeta,
  'gpt-audio-1-5': gptAudio15Meta,
  'gpt-audio-mini': gptAudioMiniMeta,
  'gpt-image-1': gptImage1Meta,
  'gpt-image-1-5': gptImage15Meta,
  'gpt-image-1-mini': gptImage1MiniMeta,
  'gpt-image-2': gptImage2Meta,
  'gpt-oss-120b': gptOss120bMeta,
  'gpt-oss-20b': gptOss20bMeta,
  'gpt-realtime': gptRealtimeMeta,
  'gpt-realtime-1-5': gptRealtime15Meta,
  'gpt-realtime-2': gptRealtime2Meta,
  'gpt-realtime-2-1': gptRealtime21Meta,
  'gpt-realtime-2-1-mini': gptRealtime21MiniMeta,
  'gpt-realtime-mini': gptRealtimeMiniMeta,
  'gpt-realtime-translate': gptRealtimeTranslateMeta,
  'gpt-realtime-whisper': gptRealtimeWhisperMeta,
  grok: grokMeta,
  hailuo: hailuoMeta,
  happyhorse: happyhorseMeta,
  hunyuan: hunyuanMeta,
  ibm: ibmMeta,
  ideogram: ideogramMeta,
  inception: inceptionMeta,
  inflection: inflectionMeta,
  internlm: internlmMeta,
  jimeng: jimengMeta,
  jina: jinaMeta,
  kimi: kimiMeta,
  kling: klingMeta,
  kolors: kolorsMeta,
  kwaipilot: kwaipilotMeta,
  lg: lgMeta,
  ling: lingMeta,
  liquid: liquidMeta,
  llava: llavaMeta,
  longcat: longcatMeta,
  menlo: menloMeta,
  meta: metaMeta,
  microsoft: microsoftMeta,
  mimo: mimoMeta,
  minimax: minimaxMeta,
  mistral: mistralMeta,
  moonshot: moonshotMeta,
  morph: morphMeta,
  nanobanana: nanobananaMeta,
  nousresearch: nousresearchMeta,
  nova: novaMeta,
  nvidia: nvidiaMeta,
  openai: openaiMeta,
  openchat: openchatMeta,
  openrouter: openrouterMeta,
  palm: palmMeta,
  perplexity: perplexityMeta,
  phind: phindMeta,
  poolside: poolsideMeta,
  qiniu: qiniuMeta,
  qwen: qwenMeta,
  relace: relaceMeta,
  rwkv: rwkvMeta,
  sensenova: sensenovaMeta,
  skywork: skyworkMeta,
  sora: soraMeta,
  spark: sparkMeta,
  stability: stabilityMeta,
  stepfun: stepfunMeta,
  suno: sunoMeta,
  tencent: tencentMeta,
  tii: tiiMeta,
  trinity: trinityMeta,
  udio: udioMeta,
  upstage: upstageMeta,
  v0: v0Meta,
  vertexai: vertexaiMeta,
  voyage: voyageMeta,
  wenxin: wenxinMeta,
  xiaomimimo: xiaomimimoMeta,
  yi: yiMeta,
  zai: zaiMeta
} as const satisfies Record<string, IconMeta>

export type ModelIconKey = keyof typeof MODEL_ICON_META_CATALOG
