/**
 * Catalog invariants — the durable guard that keeps `data/models.json` a clean catalog
 * of real creators' canonical, normalized model ids (and overrides that always resolve).
 *
 * These are STRUCTURAL invariants enforced on every CI run. Both files are generated by
 * `scripts/generate-catalog.ts` (from the `src/creators/` + `src/providers/` registries); this test
 * catches the regressions a structural check can (underscores, casing, custom SKUs, broken refs).
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { canonOf, prefixHit } from '../../scripts/canonicalize'
import { CREATORS } from '../creators'
import { isServerToolModelEligible } from '../patterns/serverToolModelEligibility'
import { SERVER_TOOL } from '../schemas/enums'
import { ModelListSchema } from '../schemas/model'
import { ProviderListSchema } from '../schemas/provider'
import { ProviderModelListSchema } from '../schemas/provider-models'
import { ReasoningWireProfileSchema } from '../schemas/reasoningWire'

const dataDir = join(fileURLToPath(import.meta.url), '..', '..', '..', 'data')
const modelsRaw = JSON.parse(readFileSync(join(dataDir, 'models.json'), 'utf8'))
const providerModelsRaw = JSON.parse(readFileSync(join(dataDir, 'provider-models.json'), 'utf8'))
const providersRaw = JSON.parse(readFileSync(join(dataDir, 'providers.json'), 'utf8'))
const models = modelsRaw.models as Array<{
  id: string
  name: string
  contextWindow?: number
  maxOutputTokens?: number
  capabilities?: string[]
  inputModalities?: string[]
  outputModalities?: string[]
  ownedBy?: string
}>
const overrides = providerModelsRaw.overrides as Array<{
  providerId: string
  modelId: string
  apiModelId?: string
  name?: string
}>
const providers = ProviderListSchema.parse(providersRaw).providers
const providerModelOverrides = ProviderModelListSchema.parse(providerModelsRaw).overrides

// normalized creator id: lowercase, alphanumerics joined by single hyphens (size/version kept)
const NORMALIZED = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
// shapes a creator never publishes: custom SKUs, double-dash vendor wrappers, routers
const JUNK = /(?:-vip|-ssvip|-cursor|-all|-nx|-gizmo|-mobile)$|--|^duo-chat-|\bauto\b/

describe('catalog invariants (data/*.json)', () => {
  const ids = models.map((m) => m.id)
  const baseIds = new Set(ids)

  it.each([
    ['mai-image-2-5', 'microsoft', 'Microsoft: MAI-Image-2.5'],
    ['recraft-v4-1-vector', 'recraft', 'Recraft: Recraft V4.1 Vector'],
    ['riverflow-v2-5-fast', 'sourceful', 'Sourceful: Riverflow V2.5 Fast'],
    ['seedream-4-5', 'bytedance', 'Seedream 4.5']
  ])('catalogs OpenRouter image model %s under its creator with its display name', (modelId, ownedBy, name) => {
    expect(models.find((model) => model.id === modelId)).toMatchObject({
      capabilities: expect.arrayContaining(['image-generation']),
      name,
      ownedBy
    })
  })

  // `listProviderPresetModels` sends `apiModelId ?? modelId` on the wire, so a row whose canonical key
  // is not the served id must carry `apiModelId` — otherwise the canonical spelling (`glm-5-2` for
  // `glm-5.2`) goes out and 404s. Generation derives both from the authored id; this catches a row
  // that reached the catalog without passing through that split.
  it('every override either is keyed canonically or carries a wire id', () => {
    const leaking = overrides
      .filter((override) => !override.apiModelId && canonOf(override.modelId) !== override.modelId)
      .map((override) => `${override.providerId}/${override.modelId}`)
    expect(leaking).toEqual([])
  })

  it('base model ids are unique', () => {
    expect(ids.filter((id, i) => ids.indexOf(id) !== i)).toEqual([])
  })

  it('base models are sorted by creator and id', () => {
    const keys = models.map((model) => `${model.ownedBy ?? ''}\0${model.id}`)
    expect(keys).toEqual([...keys].sort())
  })

  it('every base id is a normalized creator id (lowercase, single-hyphen separated)', () => {
    expect(ids.filter((id) => !NORMALIZED.test(id))).toEqual([])
  })

  it('no junk id patterns (custom SKUs / vendor wrappers / routers)', () => {
    expect(ids.filter((id) => JUNK.test(id))).toEqual([])
  })

  // Canonicalization must be idempotent on the artifact itself: a base id the canonicalizer would
  // still fold (id !== canonOf(id)) means a variant/date row leaked through a non-fixpoint strip pass
  // and coexists with (or shadows) its true base row.
  it('every base id is a canonicalization fixpoint (id === canonOf(id))', () => {
    expect(ids.filter((id) => canonOf(id) !== id)).toEqual([])
  })

  it('assigns overlapping creator prefixes to the most specific owner', () => {
    const wrongOwner = models
      .map((model) => {
        const mostSpecific = CREATORS.flatMap((creator) =>
          (creator.idPrefixes ?? [])
            .filter((prefix) => prefixHit(model.id, prefix))
            .map((prefix) => ({ creatorId: creator.id, prefix }))
        ).sort((a, b) => b.prefix.length - a.prefix.length)[0]
        return mostSpecific && mostSpecific.creatorId !== model.ownedBy
          ? `${model.id}: ${model.ownedBy} != ${mostSpecific.creatorId} (${mostSpecific.prefix})`
          : undefined
      })
      .filter(Boolean)
    expect(wrongOwner).toEqual([])
  })

  it('every override resolves to a base row or carries a standalone name', () => {
    const broken = overrides
      .filter((o) => !baseIds.has(o.modelId) && !o.name)
      .map((o) => `${o.providerId}/${o.modelId}`)
    expect(broken).toEqual([])
  })

  // OpenCode Go is one base URL over three wire protocols picked per model, and its served list comes
  // from models.dev — so a newly synced model lands here unpinned and silently falls back to
  // chat/completions (#17860). Classify it against models.dev's per-model `provider.npm`.
  it('pins an endpoint on every OpenCode Go model', () => {
    const unpinned = providerModelOverrides
      .filter((o) => o.providerId === 'opencode' && !o.endpointTypes?.length)
      .map((o) => o.modelId)
    expect(unpinned).toEqual([])
  })

  it('does not encode provider-native web search as a generic model capability', () => {
    expect(models.filter((model) => model.capabilities?.includes('web-search')).map((model) => model.id)).toEqual([])
  })

  // Image-generation models must not inherit web-search eligibility — it leaks a server tool onto image rows.
  // The sole exception is gemini-3 image (Nano Banana Pro), which genuinely grounds on Google Search;
  // every other image model (e.g. gemini-2.5-flash-image) must not carry it. The generator already strips
  // PREFIX-inherited web-search from image rows; this catches a HAND-LISTED `web-search` slipping back in.
  it('no image-generation model is web-search eligible except allowlisted gemini-3 image models', () => {
    const WEB_SEARCH_IMAGE_ALLOWLIST = new Set(['gemini-3-pro-image', 'gemini-3-pro-image-preview'])
    const offenders = models
      .filter((model) => model.capabilities?.includes('image-generation'))
      .filter((model) =>
        providers.some((provider) => isServerToolModelEligible(model.id, provider.id, SERVER_TOOL.WEB_SEARCH))
      )
      .map((model) => model.id)
      .filter((id) => !WEB_SEARCH_IMAGE_ALLOWLIST.has(id))
    expect(offenders).toEqual([])
  })

  // Web search is a text-chat server tool: a model that doesn't converse in text on both sides (TTS is
  // text→audio, transcription is audio→text, embedders output vector) must never be eligible.
  it('no non-text-chat model is web-search eligible (tts / transcription / embedding)', () => {
    const offenders = models
      .filter((model) =>
        providers.some((provider) => isServerToolModelEligible(model.id, provider.id, SERVER_TOOL.WEB_SEARCH))
      )
      .filter(
        (m) => !(m.inputModalities ?? ['text']).includes('text') || !(m.outputModalities ?? ['text']).includes('text')
      )
      .map((m) => m.id)
    expect(offenders).toEqual([])
  })

  // The loader's canonical override index (`overrideByKey`) resolves a duplicated key to the self
  // variant (`apiModelId === modelId`) — see registry-loader.ts `buildOverrideIndex`. A duplicated key
  // with NO self variant makes the winning override file-order-dependent, so forbid it.
  it('every duplicated providerId::modelId key contains a self variant', () => {
    const byKey = new Map<string, Array<(typeof overrides)[number]>>()
    for (const o of overrides) {
      const key = `${o.providerId}::${o.modelId}`
      byKey.set(key, [...(byKey.get(key) ?? []), o])
    }
    const orderDependent = [...byKey.entries()]
      .filter(([, rows]) => rows.length > 1 && !rows.some((r) => (r.apiModelId ?? r.modelId) === r.modelId))
      .map(([key]) => key)
    expect(orderDependent).toEqual([])
  })

  // `[1m]` is a Claude Code CLI suffix that raises the session's context budget: it never reaches an
  // API, so it may only appear as an apiModelId, only on that provider, only paired with the plain
  // row users pick when they don't want the extended window, and only on a model that has 1M to give.
  it('every [1m] apiModelId is a claude-code twin of a plain 1M-context row', () => {
    const contextWindowById = new Map(models.map((m) => [m.id, m.contextWindow]))
    const plainRows = new Set(
      overrides.filter((o) => (o.apiModelId ?? o.modelId) === o.modelId).map((o) => `${o.providerId}::${o.modelId}`)
    )
    const broken = overrides
      .filter((o) => (o.apiModelId ?? '').endsWith('[1m]'))
      .filter(
        (o) =>
          o.providerId !== 'claude-code' ||
          o.apiModelId !== `${o.modelId}[1m]` ||
          !plainRows.has(`${o.providerId}::${o.modelId}`) ||
          (contextWindowById.get(o.modelId) ?? 0) < 1_000_000
      )
      .map((o) => `${o.providerId}/${o.apiModelId}`)
    expect(broken).toEqual([])
  })

  // sequentialImageGeneration is a string enum in the central catalog
  // (imageParamCatalog.ts) and the Doubao API only accepts 'auto'/'disabled' — a
  // `switch` support spec here renders a boolean UI control that gets coerced
  // away before the request, silently no-opping the feature (aihubmix's
  // doubao-seedream-4-0/4-5 had this; dmxapi's doubao model already declares it
  // correctly as the reference shape).
  it('sequentialImageGeneration is never declared as a switch (must be the string enum)', () => {
    type Row = { id?: string; modelId?: string; providerId?: string; imageGeneration?: unknown }
    const allRows: Row[] = [...(modelsRaw.models as Row[]), ...(providerModelsRaw.overrides as Row[])]
    const offenders: string[] = []
    for (const row of allRows) {
      const modes = (row.imageGeneration as { modes?: Record<string, unknown> } | undefined)?.modes ?? {}
      for (const [modeName, def] of Object.entries(modes)) {
        const spec = (def as { supports?: Record<string, { type?: string }> }).supports?.sequentialImageGeneration
        if (spec?.type === 'switch') {
          offenders.push(`${row.providerId ?? 'base'}/${row.modelId ?? row.id}:${modeName}`)
        }
      }
    }
    expect(offenders).toEqual([])
  })

  it('maxOutputTokens never exceeds contextWindow', () => {
    const bad = models.filter((m) => m.contextWindow && m.maxOutputTokens && m.maxOutputTokens > m.contextWindow)
    expect(bad.map((m) => m.id)).toEqual([])
  })

  it('models.json conforms to ModelListSchema', () => {
    const r = ModelListSchema.safeParse(modelsRaw)
    expect(r.success ? [] : r.error.issues.slice(0, 5)).toEqual([])
  })

  it('provider-models.json conforms to ProviderModelListSchema', () => {
    const r = ProviderModelListSchema.safeParse(providerModelsRaw)
    expect(r.success ? [] : r.error.issues.slice(0, 5)).toEqual([])
  })

  it('Fast transports belong only to Codex and Claude Code', () => {
    expect(providers.filter((provider) => provider.fastMode).map((provider) => provider.id)).toEqual([
      'claude-code',
      'openai-codex'
    ])
  })

  it('Fast provider-model declarations require a provider transport', () => {
    const fastProviders = new Set(providers.filter((provider) => provider.fastMode).map((provider) => provider.id))
    expect(
      providerModelOverrides
        .filter((override) => override.supportsFastMode && !fastProviders.has(override.providerId))
        .map((override) => `${override.providerId}/${override.modelId}`)
    ).toEqual([])
  })

  it('budget wire operations require an explicit budget policy', () => {
    const result = ReasoningWireProfileSchema.safeParse({
      effort: {
        operations: [{ target: 'thinking_budget', value: { source: 'budget' } }]
      }
    })
    expect(result.success).toBe(false)
  })

  it('the validators actually reject known-bad shapes', () => {
    expect(NORMALIZED.test('GLM-4_5')).toBe(false) // uppercase + underscore
    expect(NORMALIZED.test('anthropic--claude-3-5-sonnet')).toBe(false) // double-dash
    expect(NORMALIZED.test('claude-3-5-sonnet@20240620')).toBe(false) // @date
    expect(JUNK.test('gpt-4o-image-vip')).toBe(true)
    expect(JUNK.test('duo-chat-gpt-5-2')).toBe(true)
    expect(JUNK.test('claude-3-5-sonnet')).toBe(false) // real id must pass
  })
})
