/**
 * Auto-generated icon meta catalog for synchronous runtime lookup
 * Do not edit manually — regenerated by the icon pipeline
 *
 * Generated at: 2026-08-10T12:29:08.781Z
 * Total icons: 158
 */
import { type IconMeta } from '../types'
import { meta as minTop3Meta } from './3min-top/meta'
import { meta as ai302Meta } from './302ai/meta'
import { meta as abacusMeta } from './abacus/meta'
import { meta as aiOnlyMeta } from './ai-only/meta'
import { meta as aiStudioMeta } from './ai-studio/meta'
import { meta as ai21Meta } from './ai21/meta'
import { meta as aihubmixMeta } from './aihubmix/meta'
import { meta as aionlabsMeta } from './aionlabs/meta'
import { meta as alayanewMeta } from './alayanew/meta'
import { meta as allenaiMeta } from './allenai/meta'
import { meta as anthropicMeta } from './anthropic/meta'
import { meta as applicationMeta } from './application/meta'
import { meta as arceeAiMeta } from './arcee-ai/meta'
import { meta as awsBedrockMeta } from './aws-bedrock/meta'
import { meta as azureaiMeta } from './azureai/meta'
import { meta as baaiMeta } from './baai/meta'
import { meta as baichuanMeta } from './baichuan/meta'
import { meta as baiduMeta } from './baidu/meta'
import { meta as baiduCloudMeta } from './baidu-cloud/meta'
import { meta as bailianMeta } from './bailian/meta'
import { meta as bflMeta } from './bfl/meta'
import { meta as bochaMeta } from './bocha/meta'
import { meta as boltNewMeta } from './bolt-new/meta'
import { meta as burncloudMeta } from './burncloud/meta'
import { meta as bytedanceMeta } from './bytedance/meta'
import { meta as cephalonMeta } from './cephalon/meta'
import { meta as cerebrasMeta } from './cerebras/meta'
import { meta as cherryinMeta } from './cherryin/meta'
import { meta as claudeCodeMeta } from './claude-code/meta'
import { meta as cloudflareMeta } from './cloudflare/meta'
import { meta as cohereMeta } from './cohere/meta'
import { meta as composioMeta } from './composio/meta'
import { meta as cozeMeta } from './coze/meta'
import { meta as dangbeiMeta } from './dangbei/meta'
import { meta as dashscopeMeta } from './dashscope/meta'
import { meta as databricksMeta } from './databricks/meta'
import { meta as deepcogitoMeta } from './deepcogito/meta'
import { meta as deepseekMeta } from './deepseek/meta'
import { meta as devvMeta } from './devv/meta'
import { meta as difyMeta } from './dify/meta'
import { meta as dmxapiMeta } from './dmxapi/meta'
import { meta as doc2xMeta } from './doc2x/meta'
import { meta as dolaMeta } from './dola/meta'
import { meta as dolphinAiMeta } from './dolphin-ai/meta'
import { meta as doubaoMeta } from './doubao/meta'
import { meta as duckMeta } from './duck/meta'
import { meta as elevenlabsMeta } from './elevenlabs/meta'
import { meta as essentialAiMeta } from './essential-ai/meta'
import { meta as exaMeta } from './exa/meta'
import { meta as feloMeta } from './felo/meta'
import { meta as firecrawlMeta } from './firecrawl/meta'
import { meta as fireworksMeta } from './fireworks/meta'
import { meta as flowithMeta } from './flowith/meta'
import { meta as gensparkMeta } from './genspark/meta'
import { meta as giteeAiMeta } from './gitee-ai/meta'
import { meta as githubMeta } from './github/meta'
import { meta as githubCopilotMeta } from './github-copilot/meta'
import { meta as glamaMeta } from './glama/meta'
import { meta as googleMeta } from './google/meta'
import { meta as gpustackMeta } from './gpustack/meta'
import { meta as grokMeta } from './grok/meta'
import { meta as groqMeta } from './groq/meta'
import { meta as higressMeta } from './higress/meta'
import { meta as huggingfaceMeta } from './huggingface/meta'
import { meta as hyperbolicMeta } from './hyperbolic/meta'
import { meta as ideogramMeta } from './ideogram/meta'
import { meta as imaMeta } from './ima/meta'
import { meta as inceptionlabsMeta } from './inceptionlabs/meta'
import { meta as infiniMeta } from './infini/meta'
import { meta as inflectionMeta } from './inflection/meta'
import { meta as intelMeta } from './intel/meta'
import { meta as internlmMeta } from './internlm/meta'
import { meta as jimengMeta } from './jimeng/meta'
import { meta as jinaMeta } from './jina/meta'
import { meta as klingMeta } from './kling/meta'
import { meta as kwaipilotMeta } from './kwaipilot/meta'
import { meta as lambdaMeta } from './lambda/meta'
import { meta as lanyunMeta } from './lanyun/meta'
import { meta as leptonMeta } from './lepton/meta'
import { meta as lingxiMeta } from './lingxi/meta'
import { meta as liquidMeta } from './liquid/meta'
import { meta as lmstudioMeta } from './lmstudio/meta'
import { meta as longcatMeta } from './longcat/meta'
import { meta as macosMeta } from './macos/meta'
import { meta as mcpMeta } from './mcp/meta'
import { meta as mcpsoMeta } from './mcpso/meta'
import { meta as metaMeta } from './meta/meta'
import { meta as metasoMeta } from './metaso/meta'
import { meta as mineruMeta } from './mineru/meta'
import { meta as minimaxMeta } from './minimax/meta'
import { meta as minimaxAgentMeta } from './minimax-agent/meta'
import { meta as mistralMeta } from './mistral/meta'
import { meta as mixedbreadMeta } from './mixedbread/meta'
import { meta as modelscopeMeta } from './modelscope/meta'
import { meta as monicaMeta } from './monica/meta'
import { meta as moonshotMeta } from './moonshot/meta'
import { meta as n8nMeta } from './n8n/meta'
import { meta as namiAiMeta } from './nami-ai/meta'
import { meta as neteaseYoudaoMeta } from './netease-youdao/meta'
import { meta as newapiMeta } from './newapi/meta'
import { meta as nomicMeta } from './nomic/meta'
import { meta as notebooklmMeta } from './notebooklm/meta'
import { meta as nousresearchMeta } from './nousresearch/meta'
import { meta as nvidiaMeta } from './nvidia/meta'
import { meta as ocoolaiMeta } from './ocoolai/meta'
import { meta as ollamaMeta } from './ollama/meta'
import { meta as openaiMeta } from './openai/meta'
import { meta as openclawMeta } from './openclaw/meta'
import { meta as openCodeGoMeta } from './opencode/meta'
import { meta as openrouterMeta } from './openrouter/meta'
import { meta as paddleocrMeta } from './paddleocr/meta'
import { meta as perplexityMeta } from './perplexity/meta'
import { meta as ph8Meta } from './ph8/meta'
import { meta as poeMeta } from './poe/meta'
import { meta as ppioMeta } from './ppio/meta'
import { meta as pulseMeta } from './pulse/meta'
import { meta as qiniuMeta } from './qiniu/meta'
import { meta as queritMeta } from './querit/meta'
import { meta as qwenMeta } from './qwen/meta'
import { meta as radeonCloudMeta } from './radeon-cloud/meta'
import { meta as recraftMeta } from './recraft/meta'
import { meta as relaceMeta } from './relace/meta'
import { meta as riverflowMeta } from './riverflow/meta'
import { meta as runwayMeta } from './runway/meta'
import { meta as searxngMeta } from './searxng/meta'
import { meta as sensetimeMeta } from './sensetime/meta'
import { meta as siliconMeta } from './silicon/meta'
import { meta as skyworkMeta } from './skywork/meta'
import { meta as smitheryMeta } from './smithery/meta'
import { meta as sophnetMeta } from './sophnet/meta'
import { meta as stabilityMeta } from './stability/meta'
import { meta as stepMeta } from './step/meta'
import { meta as streamlakeMeta } from './streamlake/meta'
import { meta as sunoMeta } from './suno/meta'
import { meta as tavilyMeta } from './tavily/meta'
import { meta as tencentCloudTiMeta } from './tencent-cloud-ti/meta'
import { meta as tesseractJsMeta } from './tesseract-js/meta'
import { meta as thinkAnyMeta } from './think-any/meta'
import { meta as tngMeta } from './tng/meta'
import { meta as togetherMeta } from './together/meta'
import { meta as twitterMeta } from './twitter/meta'
import { meta as upstageMeta } from './upstage/meta'
import { meta as vercelMeta } from './vercel/meta'
import { meta as vertexaiMeta } from './vertexai/meta'
import { meta as viduMeta } from './vidu/meta'
import { meta as volcengineMeta } from './volcengine/meta'
import { meta as voyageMeta } from './voyage/meta'
import { meta as wenxinMeta } from './wenxin/meta'
import { meta as workersAiMeta } from './workers-ai/meta'
import { meta as xiaoyiMeta } from './xiaoyi/meta'
import { meta as xinghuoMeta } from './xinghuo/meta'
import { meta as xirangMeta } from './xirang/meta'
import { meta as youMeta } from './you/meta'
import { meta as yuanbaoMeta } from './yuanbao/meta'
import { meta as zAiMeta } from './z-ai/meta'
import { meta as zeroOneMeta } from './zero-one/meta'
import { meta as zhidaMeta } from './zhida/meta'
import { meta as zhipuMeta } from './zhipu/meta'

export const PROVIDER_ICON_META_CATALOG = {
  '302ai': ai302Meta,
  '3min-top': minTop3Meta,
  abacus: abacusMeta,
  'ai-only': aiOnlyMeta,
  'ai-studio': aiStudioMeta,
  ai21: ai21Meta,
  aihubmix: aihubmixMeta,
  aionlabs: aionlabsMeta,
  alayanew: alayanewMeta,
  allenai: allenaiMeta,
  anthropic: anthropicMeta,
  application: applicationMeta,
  'arcee-ai': arceeAiMeta,
  'aws-bedrock': awsBedrockMeta,
  azureai: azureaiMeta,
  baai: baaiMeta,
  baichuan: baichuanMeta,
  baidu: baiduMeta,
  'baidu-cloud': baiduCloudMeta,
  bailian: bailianMeta,
  bfl: bflMeta,
  bocha: bochaMeta,
  'bolt-new': boltNewMeta,
  burncloud: burncloudMeta,
  bytedance: bytedanceMeta,
  cephalon: cephalonMeta,
  cerebras: cerebrasMeta,
  cherryin: cherryinMeta,
  'claude-code': claudeCodeMeta,
  cloudflare: cloudflareMeta,
  cohere: cohereMeta,
  composio: composioMeta,
  coze: cozeMeta,
  dangbei: dangbeiMeta,
  dashscope: dashscopeMeta,
  databricks: databricksMeta,
  deepcogito: deepcogitoMeta,
  deepseek: deepseekMeta,
  devv: devvMeta,
  dify: difyMeta,
  dmxapi: dmxapiMeta,
  doc2x: doc2xMeta,
  dola: dolaMeta,
  'dolphin-ai': dolphinAiMeta,
  doubao: doubaoMeta,
  duck: duckMeta,
  elevenlabs: elevenlabsMeta,
  'essential-ai': essentialAiMeta,
  exa: exaMeta,
  felo: feloMeta,
  firecrawl: firecrawlMeta,
  fireworks: fireworksMeta,
  flowith: flowithMeta,
  genspark: gensparkMeta,
  'gitee-ai': giteeAiMeta,
  github: githubMeta,
  'github-copilot': githubCopilotMeta,
  glama: glamaMeta,
  google: googleMeta,
  gpustack: gpustackMeta,
  grok: grokMeta,
  groq: groqMeta,
  higress: higressMeta,
  huggingface: huggingfaceMeta,
  hyperbolic: hyperbolicMeta,
  ideogram: ideogramMeta,
  ima: imaMeta,
  inceptionlabs: inceptionlabsMeta,
  infini: infiniMeta,
  inflection: inflectionMeta,
  intel: intelMeta,
  internlm: internlmMeta,
  jimeng: jimengMeta,
  jina: jinaMeta,
  kling: klingMeta,
  kwaipilot: kwaipilotMeta,
  lambda: lambdaMeta,
  lanyun: lanyunMeta,
  lepton: leptonMeta,
  lingxi: lingxiMeta,
  liquid: liquidMeta,
  lmstudio: lmstudioMeta,
  longcat: longcatMeta,
  macos: macosMeta,
  mcp: mcpMeta,
  mcpso: mcpsoMeta,
  meta: metaMeta,
  metaso: metasoMeta,
  mineru: mineruMeta,
  minimax: minimaxMeta,
  'minimax-agent': minimaxAgentMeta,
  mistral: mistralMeta,
  mixedbread: mixedbreadMeta,
  modelscope: modelscopeMeta,
  monica: monicaMeta,
  moonshot: moonshotMeta,
  n8n: n8nMeta,
  'nami-ai': namiAiMeta,
  'netease-youdao': neteaseYoudaoMeta,
  newapi: newapiMeta,
  nomic: nomicMeta,
  notebooklm: notebooklmMeta,
  nousresearch: nousresearchMeta,
  nvidia: nvidiaMeta,
  ocoolai: ocoolaiMeta,
  ollama: ollamaMeta,
  openai: openaiMeta,
  openclaw: openclawMeta,
  opencode: openCodeGoMeta,
  openrouter: openrouterMeta,
  paddleocr: paddleocrMeta,
  perplexity: perplexityMeta,
  ph8: ph8Meta,
  poe: poeMeta,
  ppio: ppioMeta,
  pulse: pulseMeta,
  qiniu: qiniuMeta,
  querit: queritMeta,
  qwen: qwenMeta,
  'radeon-cloud': radeonCloudMeta,
  recraft: recraftMeta,
  relace: relaceMeta,
  riverflow: riverflowMeta,
  runway: runwayMeta,
  searxng: searxngMeta,
  sensetime: sensetimeMeta,
  silicon: siliconMeta,
  skywork: skyworkMeta,
  smithery: smitheryMeta,
  sophnet: sophnetMeta,
  stability: stabilityMeta,
  step: stepMeta,
  streamlake: streamlakeMeta,
  suno: sunoMeta,
  tavily: tavilyMeta,
  'tencent-cloud-ti': tencentCloudTiMeta,
  'tesseract-js': tesseractJsMeta,
  'think-any': thinkAnyMeta,
  tng: tngMeta,
  together: togetherMeta,
  twitter: twitterMeta,
  upstage: upstageMeta,
  vercel: vercelMeta,
  vertexai: vertexaiMeta,
  vidu: viduMeta,
  volcengine: volcengineMeta,
  voyage: voyageMeta,
  wenxin: wenxinMeta,
  'workers-ai': workersAiMeta,
  xiaoyi: xiaoyiMeta,
  xinghuo: xinghuoMeta,
  xirang: xirangMeta,
  you: youMeta,
  yuanbao: yuanbaoMeta,
  'z-ai': zAiMeta,
  'zero-one': zeroOneMeta,
  zhida: zhidaMeta,
  zhipu: zhipuMeta
} as const satisfies Record<string, IconMeta>

export type ProviderIconKey = keyof typeof PROVIDER_ICON_META_CATALOG
